name: diaryapp
description: "log your days"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.2
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  crypto: ^3.0.1
  shared_preferences: ^2.3.3
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
